#Doc http://jekyllrb.com/docs/configuration/
gems:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-sitemap
safe: false
title: "SbmlViewer"
description: "The collection of transformations from SBML files into human readable formats"
logo: /assets/img/logo_isb.png
url: http://sv.insysbio.com
liquid:
  error_mode: warn
#statistics
#google_analytics: ???
yandex_metrika: 44335438
#Path for current release
distPath: online/
#SEO
facebook:
  app_id: 266737823736763
twitter:
  username: insysbio
social:
  name: InSysBio
  links:
    - https://www.facebook.com/insysbio
    - https://www.linkedin.com/insysbio
    - https://github.com/insysbio
    - https://twitter.com/insysbio
    - https://insysbio.com/en
defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/sbmlviewer_example.png


